"""empty message

Revision ID: 7ec15577e773
Revises: 
Create Date: 2023-02-24 15:05:11.275115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ec15577e773'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'cover_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('cover_url', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###
